
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
  
  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    container_name: nextjs
    ports:
      - "3000:3000"
